### ISSUE TITLE
Cross-language test suite in JSON

### ISSUE THREAD

**Issue by udhos** [johnowl/owl-rules#13]
Hello John,

What do you think about a standardized cross-language test suite in JSON for Bule?

I have converted all test cases from the Go implementation into this:
https://github.com/udhos/gobule/blob/main/parser/tests.json

The motivation is to ease sharing of the test suite across implementations in different languages.

Thanks,
Everton

**Comment by johnowl** [comment]
Hello Everton!

Nice idea to keep the implementations working the same way, I'll work on this.

Thanks

JP

**Comment by johnowl** [comment]
Hello @udhos, in this test case, because we rely on parenthesis to identify every expression, we need to add it in this expression:

Instead of the rule below, which in the currently Kotlin version an error is thrown 
```
  {
    "name": "list 1",
    "rule": "NOT [1 2 3 4] CONTAINS 4",
    "vars": "{}",
    "expected_result": "false"
  
```

We should use `NOT ([1 2 3 4] CONTAINS 4)`

Of course, it's open to discussion and any idea is welcome.

Thanks

JP

**Comment by johnowl** [comment]
@udhos I was throwing an exception on any type mismatch error, but I liked your approach to don't do it for equal and not equal operators. I'll replicate it here.

**Comment by johnowl** [comment]
@udhos  the constructions below are invalid, they only make sense for a variable, otherwise is just a more verbose way of doing things:

```
Number('12') simply use 12
List('[1 2 3 4]') simply use [1 2 3 4]
```

Thanks

JP

**Comment by johnowl** [comment]
@udhos mixing text with numbers in a list is not a valid construction.

```
['beta' 'alpha' 'has_reward_program' Number(var1)] CONTAINS 1
```
This way is valid

```
['beta' 'alpha' 'has_reward_program' var1] CONTAINS '1'
```

**Comment by johnowl** [comment]
I opened the PR, there is a slightly different version of the test suite.

**Comment by udhos** [comment]
> because we rely on parenthesis to identify every expression, we need to add it in this expression:
> 
> We should use `NOT ([1 2 3 4] CONTAINS 4)`

In current Go implementation, NOT accepts any expression, and both literal true and CONTAINS are expressions.
Also, an expression surrounded by () is also an expression.
So it accepts:

```
NOT true
NOT (true)
NOT [1 2 3 4] CONTAINS 4
NOT ([1 2 3 4] CONTAINS 4)
```

I am trying to figure out how to specify the exact syntax rule for NOT.
I mean, when NOT should or should not accept parenthesis?
Maybe parenthesis should be optional only for boolean literals?
Or NOT should always require parenthesis?

Thanks,
Everton

**Comment by johnowl** [comment]
Based on the examples, these are valid:

```
NOT true
NOT (true)
NOT ([1 2 3 4] CONTAINS 4)
```

This one `NOT [1 2 3 4] CONTAINS 4` is not valid because NOT negate the subsequent expression. In this case, the next valid expression is a list, to let it clearer, we need to use the parenthesis to negate not the list, but the CONTAINS expression as a whole. Does it make sense to you?

Thanks

JP

**Comment by udhos** [comment]
> Based on the examples, these are valid:
> 
> ```
> NOT true
> NOT (true)
> NOT ([1 2 3 4] CONTAINS 4)
> ```
> 
> This one `NOT [1 2 3 4] CONTAINS 4` is not valid because NOT negate the subsequent expression. In this case, the next valid expression is a list, to let it clearer, we need to use the parenthesis to negate not the list, but the CONTAINS expression as a whole. Does it make sense to you?

Yes, it does make sense, but I am having trouble figuring out what is the formal syntax for NOT.

I mean, currently the syntax used in Go is "NOT accepts any expression". Any expression enclosed in parenthesis is also an expression.

How should I rewrite that rule?

How about this?

1. NOT accepts only the literals 'true' and 'false' without parenthesis.
2. In any other case, NOT requires parenthesis.

Hence NOT only supports these three forms:
```
NOT true
NOT false
NOT(any_expression) // any expression other than true/false must be enclosed in parenthesis
```
Does that syntax rule seem correct for NOT?

Thanks!
Everton
