### ISSUE TITLE
Improve documentation about CurrentTime

### ISSUE THREAD

**Issue by johnowl** [johnowl/owl-rules#5]
Improve documentation in README about CurrentTime

**Comment by Saharatt593** [comment]
i can help

**Comment by Saharatt593** [comment]
> Improve documentation in README about CurrentTime

I'm not sure about the project you join hacktoberfest? 
if yes you can add the "hacktoberfest" topic to their repository if they wish to participate.
https://hacktoberfest.digitalocean.com/hacktoberfest-update
