### ISSUE TITLE
Support for Version(1.1.128)

### ISSUE THREAD

**Issue by udhos** [johnowl/owl-rules#8]
Hi John, how are you doing?

I have added support for keyword `Version(literal_version)` in the Go version, in order to support rules like this:

`Number('001001128') = Version(1.1.128)`

Test cases are available here: https://github.com/udhos/gobule/blob/main/parser/parser_test.go#L93

I am guessing that's how you intended to add the feature to owl-rules?

Cheers,
Everton

**Comment by johnowl** [comment]
Hello Everton, nice idea! I'll do that (=

Thanks

JP
